<?php
return [
    'up' => "CREATE TABLE scholarships (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            title VARCHAR(200) NOT NULL,
            slug VARCHAR(255) NOT NULL UNIQUE,
            provider_name VARCHAR(150) NOT NULL,
            provider_type VARCHAR(50) DEFAULT NULL,
            description TEXT NOT NULL,
            short_description VARCHAR(500) DEFAULT NULL,
            official_website VARCHAR(255) DEFAULT NULL,
            official_application_url VARCHAR(255) DEFAULT NULL,
            country_id BIGINT UNSIGNED DEFAULT NULL,
            study_level VARCHAR(50) DEFAULT NULL,
            funding_type VARCHAR(50) DEFAULT NULL,
            application_type VARCHAR(50) DEFAULT NULL,
            status VARCHAR(20) DEFAULT 'draft',
            verification_status VARCHAR(20) DEFAULT 'unverified',
            verified_at TIMESTAMP NULL DEFAULT NULL,
            verified_by BIGINT UNSIGNED DEFAULT NULL,
            published_at TIMESTAMP NULL DEFAULT NULL,
            application_open_date DATE DEFAULT NULL,
            application_deadline DATE DEFAULT NULL,
            created_by BIGINT UNSIGNED DEFAULT NULL,
            updated_by BIGINT UNSIGNED DEFAULT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_scholarships_slug (slug),
            INDEX idx_scholarships_country (country_id),
            INDEX idx_scholarships_status (status),
            INDEX idx_scholarships_verification (verification_status),
            INDEX idx_scholarships_deadline (application_deadline),
            FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE SET NULL,
            FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
            FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
            FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
    'down' => "DROP TABLE IF EXISTS scholarships;"
];
